kraken:
  analysis:
    results:
      root: gatling/results
  grafana:
    dashboard: grafana/grafana-gatling-dashboard.json
    user: admin
    password: kraken
  influxdb:
    user: admin
    password: kraken
    database: gatling
  security:
    realm: kraken
    web:
      id: kraken-web

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 1MB # Max file size.
      max-request-size: 10MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8083
  error:
    include-stacktrace: always

---
spring:
  profiles: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/kraken

kraken:
  storage:
    url: http://localhost:8080
  runtime:
    url: http://localhost:8082
  security:
    url: http://localhost:9080

---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kraken-keycloak:9080/auth/realms/kraken

kraken:
  storage:
    url: http://kraken-storage:8080
  runtime:
    url: http://kraken-runtime:8082
  security:
    url: http://kraken-keycloak:9080